### ISSUE TITLE
请问你有实现  Pyramidal Person Re-IDentification 的training过程吗? 

### ISSUE THREAD

**Issue by swg209** [bochuanwu/NAIC_Person_Reid#2]

**Comment by bochuanwu** [comment]
你把modeling文件夹下的baseline.py删除 把pyramidnet.py 重命名为baseline.py应该就可以了 可能要调一点地方 但主要就是这个。

**Comment by swg209** [comment]
@bochuanwu 请问 dynamic training 这一块是否有包含， 我看了代码，但是没看到有关 Random sample 和 P x K  sample 两种形式选择的代码？ 或者说应该怎么去实现dynamic training?  谢谢。

**Comment by bochuanwu** [comment]
data/samplers/triplet_sampler.py  RandomIdentitySampler

**Comment by swg209** [comment]
谢谢你的回复。 数据的读取我是清楚的，主要是pyramid论文提到的mutil loss dynamic training 算法，在具体实现的时候，最先开始选择FL(P id)和FL（P tp）是用哪种数据读取方式去计算的？

**Comment by bochuanwu** [comment]
> 谢谢你的回复。 数据的读取我是清楚的，主要是pyramid论文提到的mutil loss dynamic training 算法，在具体实现的时候，最先开始选择FL(P id)和FL（P tp）是用哪种数据读取方式去计算的？

他的dynamic training我没有复现 抱歉哈
